version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: apontaai-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: apontaai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: apontaai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
